image: maven:3.3.9-jdk-8

stages:
  - prepare
  - site

build-job: # This job runs in the build stage, which runs first.
  stage: prepare
  script:
    - ./millw -i __.checkFormat

pages:
  stage: site
  script:
    - ./millw -i __.docusaurusBuild
    - mv ./out/zio/site/docusaurusBuild/dest/build public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
